server:
  port: ${PORT}
#prod
spring:
  profiles:
    active: default
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true  # sql ??? ????? ?????.
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  type-aliases-package: com.example.nowpt.mvc.dto  # entity가 존재하는 경로작성.
  mapper-locations: mapper/**.xml        # XmlMapper.xml이 존재하는 경로작성.
#  thymeleaf:
#    cache: false
#    prefix: classpath:/static/
#    suffix: .html

logging:
  level:
    '[com.example.nowpt]': debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace  # query? ?? ?? ?? ????? ??? ? ?? ?????. TRACE Log? ?? ?????.